dlfilin/practicum-android-diploma-hh

- app/src/main/java/ru/practicum/android/diploma/common/di/DataModule.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/data/db/AppDataBase.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/data/db/dto/FavoritesDao.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/data/db/entity/FavoriteEntity.kt
add Room(entity, dao, dataBase)
> Task#14 add Room(entity, dao, dataBase)

- app/src/main/java/ru/practicum/android/diploma/common/data/network/HhApiService.kt
- app/src/main/java/ru/practicum/android/diploma/common/data/network/NetworkClient.kt
- app/src/main/java/ru/practicum/android/diploma/common/data/network/RetrofitNetworkClient.kt
- app/src/main/java/ru/practicum/android/diploma/common/data/network/dto/Resource.kt
- app/src/main/java/ru/practicum/android/diploma/common/data/network/dto/Response.kt
- app/src/main/java/ru/practicum/android/diploma/common/util/Debounce.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaRequest.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaResponse.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryRequest.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryResponse.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/EmployerDto.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/LogoUrlDto.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/SalaryDto.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancyAreaDto.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancyDto.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchRequest.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/dto/VacancySearchResponse.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/ContactsDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/EmploymentDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/ExperienceDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/PhoneDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/ScheduleDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/SimilarVacancyRequest.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/SkillsDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/VacancyDetailDto.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/VacancyDetailRequest.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/data/dto/VacancyDetailResponse.kt
Проверка наличия Интернета перед запросом
Sealed-class Resource (Success/Error) для ответов
dto-классы
debounce
> Network Client / Retrofit / DTO / Debounce

- app/src/main/res/values-night/themes.xml
- app/src/main/res/values/dimens.xml
- app/src/main/res/values/styles.xml
- app/src/main/res/values/themes.xml
- gradle/libs.versions.toml
Исправил цвет шрифта в статус баре
> Исправил шрифт и размер в bottom nav

- app/src/main/java/ru/practicum/android/diploma/favorites/domain/mapper/VacancyMapper.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyFragment.kt
> fixed #140 исправлена ошибка вывода контактов

- app/src/main/java/ru/practicum/android/diploma/favorites/domain/mapper/VacancyMapper.kt
> исправлена ошибка вывода зарплат

- app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/WorkPlaceFragment.kt
- app/src/main/res/layout/fragment_area_chooser.xml
- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/layout/fragment_work_place.xml
- app/src/main/res/values-en/strings.xml
- app/src/main/res/values/strings.xml
- app/src/main/res/values/styles.xml
Исправлена проблема невозможности удалить текст из поля зарплаты. Проблема была в зацикливании отрисовки данных фильтра из вьюмодели.
Исправлены неточности цвета в стрелочках для стран, регионов и индустрий. Несоответствие с макетом.
Исправлен баг перехода на страны и регионы вместо индустрий при клике на текст.
Убраны лишние constraint layouts для фильтров
Изменен EditText для ввовда зарплат на TextInputEditText
Затраченное время: 3 часа
> Task #160 ошибки верстки в фильтре

- app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterFragment.kt
- app/src/main/res/color/salary_field_empty.xml
- app/src/main/res/color/salary_field_filled.xml
- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/values/styles.xml
- высота
- паддинги, в том числе иконки
- спейсинг шрифтов
- цвета хинтов во всех состояниях
- maxLength 9, чтобы в Int вписаться
- убран слушатель на очистку поля, т.к. оно и так отправит пустую строку во вьюмодель
> Поправлено поле ввода зарплаты:

- app/src/main/java/ru/practicum/android/diploma/common/data/network/HhApiService.kt
- app/src/main/java/ru/practicum/android/diploma/common/mappers/FilterMapper.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaListDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaResponse.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreasDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryListDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryResponse.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepositoryImpl.kt
получение всего дерева регионов через рекурсию
Пока в Domain отправляем только регионы без стран. 
Потом можно оптимизировать - отправлять все, чтобы не грузить повторно с API
> Task#170 areas full tree

- app/src/main/java/ru/practicum/android/diploma/common/data/network/HhApiService.kt
- app/src/main/java/ru/practicum/android/diploma/common/mappers/FilterMapper.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaListDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreaResponse.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/AreasDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryListDto.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/dto/IndustryResponse.kt
- app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/CountryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/IndustryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/IndustryChooserFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/adapters/IndustryAdapter.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepositoryImpl.kt
- app/src/main/res/layout/fragment_industry_chooser.xml
Fixed #165 
- синхронизирован адаптер (выделяется строка при клике как на текст, так и на radioButton)
- сделана функциональность обновления фильтра по кнопке Выбрать
- обновление адаптера через вьюмодель, включая поиск
- скрываю клавиатуру, чтобы было видно кнопку Выбрать при выборе отрасли
- изменена верстка поиска на компонент из поиска вакансий
> отрасли обновление

- app/src/main/java/ru/practicum/android/diploma/filter/presentation/IndustryChooserScreenState.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/IndustryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/IndustryChooserFragment.kt
- app/src/main/res/layout/fragment_industry_chooser.xml
> Хранение отраслей, Loading

- app/src/main/java/ru/practicum/android/diploma/common/mappers/FilterMapper.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/AreaChooserScreenState.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/AreaViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/CountryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/WorkPlaceViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/AreaChooserFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/CountryChooserFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/WorkPlaceFragment.kt
- app/src/main/res/layout/fragment_area_chooser.xml
- app/src/main/res/layout/fragment_country_chooser.xml
добавил автоподставление страны по выбранному региону
> добавил фильтрацию регионов по выбранной стране

- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/layout/fragment_work_place.xml
- app/src/main/res/values/styles.xml
> оптимизация стилей

- app/src/main/java/ru/practicum/android/diploma/favorites/presentation/FavoriteState.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/presentation/FavoritesViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/favorites/ui/FavoritesFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/presentation/SearchViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
добавил дефолтное состояние экрана избранного, чтобы не мигал плейсхолдер о пустом списке
> добавил скрытие клавиатуры на экране поиска при совершении поиска

- app/src/main/java/ru/practicum/android/diploma/common/util/Formatter.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterFragment.kt
Убрал зависимости от моделей - перевод в строку
> перенес метод подготовки строки Страны для фильтра в Formatter

- app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterViewModel.kt
Reverts dlfilin/practicum-android-diploma-hh#241
> Revert "Task#239 debounce salary"

- app/src/main/java/ru/practicum/android/diploma/filter/data/repository/FilterRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/filter/domain/api/FilterRepository.kt
- app/src/main/java/ru/practicum/android/diploma/filter/domain/impl/FilterInteractorImpl.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/AreaViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/data/repository/SearchRepositoryImpl.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchInteractor.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/api/SearchRepository.kt
- app/src/main/java/ru/practicum/android/diploma/search/domain/impl/SearchInteractorImpl.kt
Reverts dlfilin/practicum-android-diploma-hh#240
> Revert "Task229   get areas"

- app/src/main/java/ru/practicum/android/diploma/filter/presentation/AreaViewModel.kt
Reverts dlfilin/practicum-android-diploma-hh#238
> Revert "Task#237 refactoring get country for area"

- app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/IndustryViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/presentation/WorkPlaceViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/FilterFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/IndustryChooserFragment.kt
- app/src/main/java/ru/practicum/android/diploma/filter/ui/WorkPlaceFragment.kt
Reverts dlfilin/practicum-android-diploma-hh#236
> Revert "Изменил название функции сохранения настроек в память телефона"

- app/src/main/res/values/styles.xml
Reverts dlfilin/practicum-android-diploma-hh#234
> Revert "Исправлен TextAppearance.App.Subtitle1"

- app/src/main/res/layout/fragment_filter.xml
- app/src/main/res/values/styles.xml
Reverts dlfilin/practicum-android-diploma-hh#232
> Revert "Исправлен allcaps в кнопках"

- app/src/main/java/ru/practicum/android/diploma/filter/presentation/FilterViewModel.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SearchFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/SimilarVacanciesFragment.kt
- app/src/main/java/ru/practicum/android/diploma/search/ui/adapter/SearchAdapter.kt
- app/src/main/java/ru/practicum/android/diploma/vacancy/ui/VacancyFragment.kt
- app/src/main/res/values-en/strings.xml
-another placeholder for Vacancy
-strings(en) - minor changes
> -List Adapter in Search and Similar
